import mongoose from 'mongoose';
import { randomBytes } from 'node:crypto';
import { Ticket, Message, TicketEvent, User } from '../models/index.js';
import { ApiError, type Identity } from '../middleware/security.js';
export const transitions:Record<string,string[]>={new:['open','resolved'],open:['waiting_on_customer','resolved'],waiting_on_customer:['open','resolved'],resolved:['open','closed'],closed:['open']};
export async function visibleTicket(id:string,identity:Identity){if(!mongoose.isValidObjectId(id))throw new ApiError(400,'Invalid ticket ID');const ticket=await Ticket.findOne({_id:id,...(identity.role==='customer'?{customerId:identity.id}:{})});if(!ticket)throw new ApiError(404,'Ticket not found');return ticket;}
export async function createTicket(identity:Identity,input:{subject:string;description:string}){let id='';await mongoose.connection.transaction(async session=>{const [ticket]=await Ticket.create([{...input,customerId:identity.id,ticketNumber:`SP-${randomBytes(6).toString('hex').toUpperCase()}`}],{session});id=String(ticket!._id);await Message.create([{ticketId:id,authorId:identity.id,body:input.description,visibility:'public'}],{session});await TicketEvent.create([{ticketId:id,actorId:identity.id,type:'created'}],{session});});return visibleTicket(id,identity);}
export async function mutateTicket(id:string,identity:Identity,version:number,action:{status?:string;reason?:string;assignedAgentId?:string|null;category?:string;priority?:string;body?:string;visibility?:'public'|'internal'}){await mongoose.connection.transaction(async session=>{const ticket=await visibleTicket(id,identity);ticket.$session(session);if(ticket.__v!==version)throw new ApiError(409,'Ticket changed; refresh before retrying');if(identity.role==='customer' && (action.visibility==='internal'||!action.body||action.status||action.category||action.priority||action.assignedAgentId!==undefined))throw new ApiError(403,'Action not permitted');const before={status:ticket.status,category:ticket.category,priority:ticket.priority,assignedAgentId:ticket.assignedAgentId};if(action.status){if(!transitions[ticket.status]?.includes(action.status))throw new ApiError(409,'Invalid status transition');if(ticket.status==='closed'&&!action.reason?.trim())throw new ApiError(400,'Reopening a closed ticket requires a reason');ticket.status=action.status as typeof ticket.status;}
if(action.assignedAgentId!==undefined){if(action.assignedAgentId && !await User.exists({_id:action.assignedAgentId,active:true,role:{$in:['agent','admin']}}))throw new ApiError(400,'Assignee must be active staff');ticket.assignedAgentId=action.assignedAgentId ? new mongoose.Types.ObjectId(action.assignedAgentId):null;if(ticket.status==='new')ticket.status='open';}
if(action.category)ticket.category=action.category as typeof ticket.category;if(action.priority)ticket.priority=action.priority as typeof ticket.priority;
if(action.body){if(identity.role==='customer'&&ticket.status==='closed')throw new ApiError(409,'Closed tickets are read only');const visibility=action.visibility || 'public';await Message.create([{ticketId:id,authorId:identity.id,body:action.body,visibility}],{session});if(visibility==='public'){if(identity.role!=='customer'&&!ticket.firstRespondedAt)ticket.firstRespondedAt=new Date();if(ticket.status==='new'||(identity.role==='customer'&&['waiting_on_customer','resolved'].includes(ticket.status)))ticket.status='open';}}
if(ticket.status==='resolved'&&before.status!=='resolved')ticket.resolvedAt=new Date();if(ticket.status==='open')ticket.resolvedAt=null;if(ticket.status==='closed')ticket.closedAt=new Date();else ticket.closedAt=null;
await ticket.save({session});await TicketEvent.create([{ticketId:id,actorId:identity.id,type:action.body?(action.visibility==='internal'?'internal_note':'public_reply'):'updated',before,after:{status:ticket.status,category:ticket.category,priority:ticket.priority,assignedAgentId:ticket.assignedAgentId,reason:action.reason}}],{session});});return visibleTicket(id,identity);}
